export const TYPES = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_ONE_FROM_CART: 'REMOVE_ONE_FROM_CART',
    REMOVE_ALL_FROM_CART: 'REMOVE_ALL_FROM_CART',
    CLEAR_CART: 'CLEAR_CART',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS'
}